const transactions = [
  {
    id: 1,
    date: '23-May-26',
    description: 'Amazon Shopping',
    category: 'Shopping',
    type: 'debit',
    withdrawAmount: 200,
    creditAmount: '',
    balance: 8315.25,
  },
  {
    id: 2,
    date: '22-May-26',
    description: 'Starbucks Coffee',
    category: 'Food',
    type: 'debit',
    withdrawAmount: 420,
    creditAmount: '',
    balance: 8515.25,
  },
  {
    id: 3,
    date: '21-May-26',
    description: 'Uber Ride',
    category: 'Travel',
    type: 'debit',
    withdrawAmount: 610,
    creditAmount: '',
    balance: 8935.25,
  },
  {
    id: 4,
    date: '20-May-26',
    description: 'Netflix',
    category: 'Subscription',
    type: 'credit',
    withdrawAmount: '',
    creditAmount: 562,
    balance: 9545.25,
  },
  {
    id: 5,
    date: '19-May-26',
    description: 'Salary Credit',
    category: 'Income',
    type: 'credit',
    withdrawAmount: '',
    creditAmount: 95000,
    balance: 10194.25,
  },
]

export default transactions;